/**
 * Synapse Lab - Core Simulation Engine & UI Controller
 * Dragon Hatchling (BDH) Synaptic Memory & Sparse Activations
 * Integrated with Python Research Backend (associations.json & benchmarks.json)
 */

import associationsData from "../python/data/associations.json";
import benchmarksData from "../python/data/benchmarks.json";

// Simulation Constants
const N = associationsData?.metadata?.dimension || 64;

// Fallback Capital Facts in case JSON structure is incomplete
const FALLBACK_FACTS = [
  { key: "Paris", value: "France" },
  { key: "Tokyo", value: "Japan" },
  { key: "Cairo", value: "Egypt" },
  { key: "Berlin", value: "Germany" },
  { key: "Rome", value: "Italy" },
  { key: "Madrid", value: "Spain" },
  { key: "Ottawa", value: "Canada" },
  { key: "Beijing", value: "China" },
  { key: "Seoul", value: "South Korea" },
  { key: "Brasilia", value: "Brazil" },
  { key: "Canberra", value: "Australia" },
  { key: "New Delhi", value: "India" },
  { key: "London", value: "UK" },
  { key: "Washington", value: "USA" },
  { key: "Bangkok", value: "Thailand" },
  { key: "Nairobi", value: "Kenya" },
  { key: "Buenos Aires", value: "Argentina" },
  { key: "Oslo", value: "Norway" },
  { key: "Athens", value: "Greece" },
  { key: "Rabat", value: "Morocco" },
];

// Load factual associations from python/data/associations.json
const BASE_FACTS = (associationsData?.facts && associationsData.facts.length > 0)
  ? associationsData.facts.map((f) => ({ key: f.key, value: f.value }))
  : JSON.parse(JSON.stringify(FALLBACK_FACTS));

// Append calibrated crosstalk probe pairs generated by PyTorch backend
if (associationsData?.crosstalk_probe) {
  const probe = associationsData.crosstalk_probe;
  BASE_FACTS.push({ key: probe.item_a.key, value: probe.item_a.value });
  BASE_FACTS.push({ key: probe.item_b.key, value: probe.item_b.value });
}

// Continuous Autoplay Sequence Script
const AUTOPLAY_CYCLE = [
  { facts: 3, k: 3, lambda: 1.00, context: 500 },
  { facts: 5, k: 3, lambda: 1.00, context: 1200 },
  { facts: 8, k: 4, lambda: 0.98, context: 2500 },
  { facts: 12, k: 4, lambda: 0.96, context: 4000 },
  { facts: 16, k: 5, lambda: 0.94, context: 6500 },
  { facts: 8, k: 18, lambda: 0.98, context: 5000 },
  { facts: 4, k: 3, lambda: 1.00, context: 1000 },
];

// State
const state = {
  k: 4, // Sparsity (1-64)
  factsCount: 3, // Facts written (1-N)
  lambda: 1.0, // Decay rate (0.90-1.00)
  contextTokens: 1000, // Context length T for KV-cache memory simulation
  facts: JSON.parse(JSON.stringify(BASE_FACTS)),
  selectedQueryKey: BASE_FACTS[0]?.key || "Paris",
  currentTab: "matrix", // 'matrix' | 'deepdive'

  // Matrix M in R^(64x64), stored as Float64Array of length 4096
  M: new Float64Array(N * N),

  // Cache of computed concept vectors and active indices
  cache: new Map(),

  // Animation tracking
  lastWriteAnimation: null, // { factIdx, startTime }
  tourActive: false,
  tourStep: 0,
  tourRaf: null,

  // Autoplay tracking
  autoplayActive: false,
  autoplayIntervalId: null,
  autoplayStepIndex: 0,
};

// Seed concept vector cache with calibrated vectors from Python backend
function seedBackendVectors() {
  if (associationsData?.concepts) {
    for (const [conceptName, data] of Object.entries(associationsData.concepts)) {
      const key = conceptName.trim().toLowerCase();
      const vec = new Float64Array(N);
      data.vector.forEach((val, idx) => {
        if (idx < N) vec[idx] = val;
      });
      state.cache.set(key, vec);
    }
  }

  // Seed crosstalk probe vectors
  if (associationsData?.crosstalk_probe) {
    const probe = associationsData.crosstalk_probe;
    const keyA = probe.item_a.key.trim().toLowerCase();
    const vecA = new Float64Array(N);
    probe.item_a.vector.forEach((v, i) => { if (i < N) vecA[i] = v; });
    state.cache.set(keyA, vecA);

    const keyB = probe.item_b.key.trim().toLowerCase();
    const vecB = new Float64Array(N);
    probe.item_b.vector.forEach((v, i) => { if (i < N) vecB[i] = v; });
    state.cache.set(keyB, vecB);
  }
}

// Deterministic Hash (FNV-1a 32-bit)
function hashString(str) {
  let h = 2166136261 >>> 0;
  const s = String(str).trim().toLowerCase();
  for (let i = 0; i < s.length; i++) {
    h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  }
  return h >>> 0;
}

// Deterministic Mulberry32 PRNG
function mulberry32(seed) {
  return function () {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Deterministic vector in R^64 with non-negative values in [0, 1)
function getConceptVector(str) {
  const key = String(str).trim().toLowerCase();
  if (state.cache.has(key)) {
    return state.cache.get(key);
  }
  const seed = hashString(key);
  const rng = mulberry32(seed);
  const vec = new Float64Array(N);
  for (let i = 0; i < N; i++) {
    vec[i] = rng();
  }
  state.cache.set(key, vec);
  return vec;
}

// topk_relu(v, k): keep top-k largest values, zero the rest, clamp negatives to 0
function topk_relu(v, k) {
  const indexed = [];
  for (let i = 0; i < N; i++) {
    indexed.push({ idx: i, val: Math.max(0, v[i]) });
  }
  indexed.sort((a, b) => b.val - a.val);

  const res = new Float64Array(N);
  const activeCount = Math.min(k, N);
  for (let i = 0; i < activeCount; i++) {
    if (indexed[i].val > 0) {
      res[indexed[i].idx] = indexed[i].val;
    }
  }
  return res;
}

// Vector L2 norm
function l2_norm(v) {
  let sum = 0;
  for (let i = 0; i < N; i++) {
    sum += v[i] * v[i];
  }
  return Math.sqrt(sum);
}

// Vector L2 normalization
function normalize(v) {
  const norm = l2_norm(v);
  const res = new Float64Array(N);
  if (norm < 1e-12) return res;
  for (let i = 0; i < N; i++) {
    res[i] = v[i] / norm;
  }
  return res;
}

// Cosine similarity
function cosine_similarity(u, v) {
  const normU = l2_norm(u);
  const normV = l2_norm(v);
  if (normU < 1e-12 || normV < 1e-12) return 0;
  let dot = 0;
  for (let i = 0; i < N; i++) {
    dot += u[i] * v[i];
  }
  return dot / (normU * normV);
}

/**
 * Recompute the full Synapse Matrix M
 * M <- lambda * M + y * x^T for each written fact in sequence
 */
function recomputeMatrix(triggerAnimation = false) {
  state.M.fill(0);

  const writtenFacts = state.facts.slice(0, state.factsCount);

  for (let p = 0; p < writtenFacts.length; p++) {
    const fact = writtenFacts[p];
    const keyVec = getConceptVector(fact.key);
    const valVec = getConceptVector(fact.value);

    const x = normalize(topk_relu(keyVec, state.k));
    const y = normalize(topk_relu(valVec, state.k));

    for (let i = 0; i < N; i++) {
      const yi = y[i];
      for (let j = 0; j < N; j++) {
        const idx = i * N + j;
        state.M[idx] = state.lambda * state.M[idx] + yi * x[j];
      }
    }
  }

  if (triggerAnimation && writtenFacts.length > 0) {
    state.lastWriteAnimation = {
      factIdx: writtenFacts.length - 1,
      startTime: performance.now(),
    };
  }

  renderMatrix();
  updateMatrixStats();
  renderRecall();
}

/**
 * Viridis Colormap for Synaptic Fast Weights
 */
function getWeightColor(val, maxVal) {
  if (val <= 1e-6) {
    return [10, 14, 23, 255]; // Baseline dark slate (#0a0e17)
  }
  const denom = maxVal > 0 ? maxVal : 1;
  const t = Math.min(1, Math.max(0, val / denom));

  let r, g, b;
  if (t < 0.25) {
    const factor = t / 0.25;
    r = Math.round(10 + (59 - 10) * factor);
    g = Math.round(14 + (82 - 14) * factor);
    b = Math.round(23 + (139 - 23) * factor);
  } else if (t < 0.50) {
    const factor = (t - 0.25) / 0.25;
    r = Math.round(59 + (33 - 59) * factor);
    g = Math.round(82 + (145 - 82) * factor);
    b = Math.round(139 + (140 - 139) * factor);
  } else if (t < 0.75) {
    const factor = (t - 0.50) / 0.25;
    r = Math.round(33 + (94 - 33) * factor);
    g = Math.round(145 + (201 - 145) * factor);
    b = Math.round(140 + (98 - 140) * factor);
  } else {
    const factor = (t - 0.75) / 0.25;
    r = Math.round(94 + (253 - 94) * factor);
    g = Math.round(201 + (231 - 201) * factor);
    b = Math.round(98 + (37 - 98) * factor);
  }

  return [r, g, b, 255];
}

/**
 * Draw 64x64 canvas heatmap
 */
const offscreenCanvas = document.createElement("canvas");
offscreenCanvas.width = N;
offscreenCanvas.height = N;
const offscreenCtx = offscreenCanvas.getContext("2d");
const imgData = offscreenCtx.createImageData(N, N);

function renderMatrix() {
  const canvas = document.getElementById("synapse-canvas");
  if (!canvas) return;
  const ctx = canvas.getContext("2d");

  let maxWeight = 0;
  for (let i = 0; i < N * N; i++) {
    if (state.M[i] > maxWeight) {
      maxWeight = state.M[i];
    }
  }
  if (maxWeight < 0.5) maxWeight = 0.5;

  const data = imgData.data;
  for (let i = 0; i < N * N; i++) {
    const val = state.M[i];
    const [r, g, b, a] = getWeightColor(val, maxWeight);
    const pixelIdx = i * 4;
    data[pixelIdx] = r;
    data[pixelIdx + 1] = g;
    data[pixelIdx + 2] = b;
    data[pixelIdx + 3] = a;
  }
  offscreenCtx.putImageData(imgData, 0, 0);

  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.drawImage(offscreenCanvas, 0, 0, canvas.width, canvas.height);

  ctx.strokeStyle = "rgba(255, 255, 255, 0.03)";
  ctx.lineWidth = 0.5;
  const step = canvas.width / N;
  for (let i = 0; i <= N; i += 8) {
    ctx.beginPath();
    ctx.moveTo(i * step, 0);
    ctx.lineTo(i * step, canvas.height);
    ctx.stroke();

    ctx.beginPath();
    ctx.moveTo(0, i * step);
    ctx.lineTo(canvas.width, i * step);
    ctx.stroke();
  }

  if (state.lastWriteAnimation) {
    const elapsed = performance.now() - state.lastWriteAnimation.startTime;
    if (elapsed < 400) {
      const alpha = (1 - elapsed / 400) * 0.35;
      const newestFact = state.facts[state.lastWriteAnimation.factIdx];
      if (newestFact) {
        const keyVec = getConceptVector(newestFact.key);
        const valVec = getConceptVector(newestFact.value);
        const x = topk_relu(keyVec, state.k);
        const y = topk_relu(valVec, state.k);

        ctx.fillStyle = `rgba(56, 189, 248, ${alpha})`;
        for (let j = 0; j < N; j++) {
          if (x[j] > 0) {
            ctx.fillRect(j * step, 0, step, canvas.height);
          }
        }
        for (let i = 0; i < N; i++) {
          if (y[i] > 0) {
            ctx.fillRect(0, i * step, canvas.width, step);
          }
        }
        ctx.fillStyle = `rgba(253, 231, 37, ${alpha * 1.6})`;
        for (let i = 0; i < N; i++) {
          if (y[i] > 0) {
            for (let j = 0; j < N; j++) {
              if (x[j] > 0) {
                ctx.fillRect(j * step, i * step, step, step);
              }
            }
          }
        }
      }
      requestAnimationFrame(renderMatrix);
    } else {
      state.lastWriteAnimation = null;
    }
  }
}

/**
 * Matrix statistics below canvas
 */
function updateMatrixStats() {
  let nonZeroCount = 0;
  let sumSq = 0;
  let maxW = 0;

  for (let i = 0; i < N * N; i++) {
    const val = state.M[i];
    if (val > 1e-5) {
      nonZeroCount++;
    }
    sumSq += val * val;
    if (val > maxW) maxW = val;
  }

  const fillPercent = ((nonZeroCount / (N * N)) * 100).toFixed(1);
  const frobNorm = Math.sqrt(sumSq).toFixed(3);

  const fillElem = document.getElementById("stat-fill");
  const frobElem = document.getElementById("stat-frob");
  const maxElem = document.getElementById("stat-max");
  const scaleMaxElem = document.getElementById("scale-max-label");

  if (fillElem) fillElem.textContent = `${fillPercent}%`;
  if (frobElem) frobElem.textContent = frobNorm;
  if (maxElem) maxElem.textContent = maxW.toFixed(3);
  if (scaleMaxElem) scaleMaxElem.textContent = `Max: ${maxW.toFixed(3)}`;
}

/**
 * Recall memory using selected query key
 */
function renderRecall() {
  const query = state.selectedQueryKey;
  const queryVec = getConceptVector(query);
  const x = normalize(topk_relu(queryVec, state.k));

  const y_hat = new Float64Array(N);
  for (let i = 0; i < N; i++) {
    let sum = 0;
    const rowOffset = i * N;
    for (let j = 0; j < N; j++) {
      sum += state.M[rowOffset + j] * x[j];
    }
    y_hat[i] = sum;
  }

  const matchedFact = state.facts.find(
    (f) => f.key.toLowerCase() === query.toLowerCase()
  );
  const groundTruthVal = matchedFact ? matchedFact.value : "None";

  const candidates = [];
  for (let i = 0; i < state.facts.length; i++) {
    const fact = state.facts[i];
    const valVec = getConceptVector(fact.value);
    const targetY = normalize(topk_relu(valVec, state.k));
    const score = cosine_similarity(y_hat, targetY);
    candidates.push({
      key: fact.key,
      value: fact.value,
      score: Math.max(0, score),
      isWritten: i < state.factsCount,
    });
  }

  candidates.sort((a, b) => b.score - a.score);

  const topMatch = candidates[0] || { value: "Unknown", score: 0 };
  const secondMatch = candidates[1] || { value: "Unknown", score: 0 };
  const retrievedVal = topMatch.value;
  const topScore = topMatch.score;
  const margin = topScore - secondMatch.score;

  const isTargetFirst = retrievedVal.toLowerCase() === groundTruthVal.toLowerCase();
  const isHighFidelity = isTargetFirst && topScore >= 0.75 && margin >= 0.15;
  const isCrosstalk = isTargetFirst && !isHighFidelity;
  const isInterference = !isTargetFirst || (state.k >= 24 && state.factsCount >= 10);

  const retrievedElem = document.getElementById("result-retrieved");
  const groundTruthElem = document.getElementById("result-groundtruth");
  const statusBadgeElem = document.getElementById("result-status-badge");
  const scoreElem = document.getElementById("result-score");
  const confBarElem = document.getElementById("result-conf-bar");

  if (retrievedElem) retrievedElem.textContent = retrievedVal;
  if (groundTruthElem) groundTruthElem.textContent = groundTruthVal;

  if (scoreElem) {
    scoreElem.textContent = `cos(ŷ, y) = ${topScore.toFixed(4)}`;
  }

  if (confBarElem) {
    const percent = Math.min(100, Math.round(topScore * 100));
    confBarElem.style.width = `${percent}%`;
    if (isInterference) {
      confBarElem.className = "h-full rounded-full transition-all duration-300 bg-rose-500";
    } else if (isCrosstalk) {
      confBarElem.className = "h-full rounded-full transition-all duration-300 bg-amber-500";
    } else {
      confBarElem.className = "h-full rounded-full transition-all duration-300 bg-emerald-500";
    }
  }

  if (statusBadgeElem) {
    if (isInterference) {
      statusBadgeElem.innerHTML = `
        <span class="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-rose-500/15 text-rose-400 border border-rose-500/30">
          <svg class="w-3.5 h-3.5 text-rose-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M6 18L18 6M6 6l12 12" />
          </svg>
          CATASTROPHIC INTERFERENCE
        </span>
      `;
    } else if (isCrosstalk) {
      statusBadgeElem.innerHTML = `
        <span class="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-amber-500/15 text-amber-400 border border-amber-500/30">
          <svg class="w-3.5 h-3.5 text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          SEVERE CROSSTALK (MARGIN ${(margin * 100).toFixed(0)}%)
        </span>
      `;
    } else {
      statusBadgeElem.innerHTML = `
        <span class="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-500/15 text-emerald-400 border border-emerald-500/30">
          <svg class="w-3.5 h-3.5 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M5 13l4 4L19 7" />
          </svg>
          HIGH-FIDELITY MATCH
        </span>
      `;
    }
  }

  const top5 = candidates.slice(0, 5);
  const chartElem = document.getElementById("candidates-chart");
  if (chartElem) {
    chartElem.innerHTML = top5
      .map((c, idx) => {
        const isGround = c.value.toLowerCase() === groundTruthVal.toLowerCase();
        const barWidth = Math.max(2, Math.min(100, Math.round(c.score * 100)));
        let barColor = "bg-sky-600/70";
        if (isGround) {
          barColor = isInterference
            ? "bg-gradient-to-r from-amber-500 to-rose-500"
            : isCrosstalk
              ? "bg-amber-400"
              : "bg-gradient-to-r from-sky-500 to-emerald-400";
        }
        return `
          <div class="flex items-center gap-2 text-xs">
            <div class="w-4 text-slate-500 font-mono text-[10px]">#${idx + 1}</div>
            <div class="w-24 truncate font-medium ${isGround ? "text-emerald-300 font-semibold" : "text-slate-300"}">${c.value}</div>
            <div class="flex-1 bg-[#070a10] border border-[#1c2638] rounded-full h-2 overflow-hidden">
              <div class="${barColor} h-full rounded-full transition-all duration-300" style="width: ${barWidth}%"></div>
            </div>
            <div class="w-12 text-right font-mono text-[11px] text-slate-400">${c.score.toFixed(3)}</div>
          </div>
        `;
      })
      .join("");
  }
}

/**
 * Render Fact list with inline editable inputs & search filter
 */
let factSearchQuery = "";

function renderFactList() {
  const listElem = document.getElementById("fact-list-container");
  if (!listElem) return;

  const countPill = document.getElementById("fact-count-pill");
  if (countPill) {
    countPill.textContent = `${state.factsCount} of ${state.facts.length} Active`;
  }

  const query = factSearchQuery.toLowerCase();
  const html = state.facts
    .map((fact, idx) => {
      const isWritten = idx < state.factsCount;
      const matchesSearch =
        !query ||
        fact.key.toLowerCase().includes(query) ||
        fact.value.toLowerCase().includes(query);

      if (!matchesSearch) return "";

      const isProbe = fact.key.startsWith("Interference");
      const probeBadge = isProbe
        ? `<span class="text-[9px] font-mono px-1 py-0.5 bg-amber-950/80 text-amber-400 border border-amber-800/40 rounded mr-1">PROBE</span>`
        : "";

      return `
        <div class="flex items-center gap-2 p-2 rounded-lg text-xs transition-all ${isWritten
          ? "bg-[#152033] border border-sky-500/30 text-slate-200"
          : "bg-[#070a10] border border-[#1c2638] text-slate-500 opacity-60"
        }">
          <span class="w-4 text-center font-mono text-[11px] ${isWritten ? "text-sky-400 font-bold" : "text-slate-600"}">${idx + 1}</span>
          <div class="flex items-center w-28">
            ${probeBadge}
            <input 
              type="text" 
              value="${fact.key}" 
              data-index="${idx}" 
              data-field="key" 
              class="fact-input bg-transparent border-b border-transparent hover:border-[#27374f] focus:border-sky-500 focus:bg-[#070a10] px-1 py-0.5 rounded outline-none w-full text-slate-200 font-medium"
            />
          </div>
          <span class="text-slate-500">→</span>
          <input 
            type="text" 
            value="${fact.value}" 
            data-index="${idx}" 
            data-field="value" 
            class="fact-input bg-transparent border-b border-transparent hover:border-[#27374f] focus:border-sky-500 focus:bg-[#070a10] px-1 py-0.5 rounded outline-none flex-1 text-slate-200"
          />
          <button 
            type="button" 
            data-key="${fact.key}" 
            class="fact-query-btn text-[10px] px-1.5 py-0.5 rounded font-mono cursor-pointer state-trans ${isWritten
          ? "bg-sky-950/80 hover:bg-sky-900 text-sky-300 border border-sky-800/50"
          : "bg-[#0c1322] text-slate-600 hover:text-slate-400"
        }"
            title="Set as active query"
          >
            ${isWritten ? "ACTIVE" : "PENDING"}
          </button>
        </div>
      `;
    })
    .join("");

  listElem.innerHTML = html;

  const inputs = listElem.querySelectorAll(".fact-input");
  inputs.forEach((input) => {
    input.addEventListener("change", (e) => {
      const target = e.target;
      const index = parseInt(target.getAttribute("data-index"), 10);
      const field = target.getAttribute("data-field");
      state.facts[index][field] = target.value.trim();
      state.cache.clear();
      seedBackendVectors();
      updateQueryDropdown();
      recomputeMatrix(true);
    });
  });

  const queryBtns = listElem.querySelectorAll(".fact-query-btn");
  queryBtns.forEach((btn) => {
    btn.addEventListener("click", () => {
      const key = btn.getAttribute("data-key");
      if (key) {
        state.selectedQueryKey = key;
        updateQueryDropdown();
        renderRecall();
      }
    });
  });
}

/**
 * Update the query dropdown with current facts
 */
function updateQueryDropdown() {
  const selectElem = document.getElementById("query-select");
  if (!selectElem) return;

  const currentVal = state.selectedQueryKey;
  selectElem.innerHTML = state.facts
    .map((fact, idx) => {
      const isWritten = idx < state.factsCount;
      return `<option value="${fact.key}" ${fact.key === currentVal ? "selected" : ""
        }>${fact.key} (${fact.value}) ${isWritten ? "• in matrix" : "• unwritten"}</option>`;
    })
    .join("");
}

/**
 * Update KaTeX formula with current lambda substituted
 */
function updateFormulaDisplay() {
  const formulaElem = document.getElementById("active-formula");
  if (!formulaElem) return;

  const lambdaStr = state.lambda.toFixed(2);
  const latex = `M \\leftarrow ${lambdaStr} \\cdot M + y x^\\top`;
  if (typeof window !== "undefined" && window.katex) {
    try {
      window.katex.render(latex, formulaElem, { displayMode: false, throwOnError: false });
    } catch {
      formulaElem.textContent = `M ← ${lambdaStr}·M + yxᵀ`;
    }
  } else {
    formulaElem.textContent = `M ← ${lambdaStr}·M + yxᵀ`;
  }
}

/**
 * Updates the KV-cache vs. BDH memory footprint comparison meter
 * BDH Synapses: Fixed N x N x 8 bytes (Float64) = 32,768 Bytes (32.77 KB)
 * Transformer KV-Cache: 2 * L * T * N * 4 bytes (FP32 K and V tensors, L=1 layer)
 */
function updateMemoryMeter() {
  const bdhBytes = N * N * 8; // 64 * 64 * 8 = 32,768 bytes (32.77 KB)
  const kvBytes = 2 * 1 * state.contextTokens * N * 4; // 2 * L=1 * T * d=64 * 4 bytes = 512 * T bytes

  const bdhElem = document.getElementById("meter-bdh-bytes");
  const kvElem = document.getElementById("meter-kv-bytes");
  const kvBar = document.getElementById("meter-kv-bar");
  const contextDisplay = document.getElementById("val-context");

  if (bdhElem) {
    bdhElem.textContent = `${(bdhBytes / 1000).toFixed(2)} KB`;
  }

  if (kvElem) {
    if (kvBytes >= 1000 * 1000) {
      kvElem.textContent = `${(kvBytes / (1000 * 1000)).toFixed(2)} MB`;
    } else {
      kvElem.textContent = `${(kvBytes / 1000).toFixed(2)} KB`;
    }
  }

  if (contextDisplay) {
    contextDisplay.textContent = `T = ${state.contextTokens.toLocaleString()} tokens`;
  }

  if (kvBar) {
    const percentage = Math.min(100, Math.max(5, (state.contextTokens / 10000) * 100));
    kvBar.style.width = `${percentage}%`;
  }
}

/**
 * Handle hover on Synapse Canvas for tooltip
 */
function setupCanvasTooltip() {
  const canvas = document.getElementById("synapse-canvas");
  const tooltip = document.getElementById("matrix-tooltip");
  if (!canvas || !tooltip) return;

  canvas.addEventListener("mousemove", (e) => {
    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    const col = Math.floor((x / rect.width) * N);
    const row = Math.floor((y / rect.height) * N);

    if (col < 0 || col >= N || row < 0 || row >= N) {
      tooltip.style.display = "none";
      return;
    }

    const cellWeight = state.M[row * N + col];

    const contributing = [];
    const writtenFacts = state.facts.slice(0, state.factsCount);
    for (let p = 0; p < writtenFacts.length; p++) {
      const fact = writtenFacts[p];
      const keyVec = getConceptVector(fact.key);
      const valVec = getConceptVector(fact.value);
      const xVec = normalize(topk_relu(keyVec, state.k));
      const yVec = normalize(topk_relu(valVec, state.k));

      if (yVec[row] > 0 && xVec[col] > 0) {
        contributing.push({
          fact: `${fact.key} → ${fact.value}`,
          contrib: yVec[row] * xVec[col],
        });
      }
    }

    let tooltipContent = `
      <div class="font-mono text-sky-300 font-bold border-b border-[#1c2638] pb-1 mb-1.5 flex justify-between text-xs">
        <span>Synapse M[${row}, ${col}]</span>
        <span class="text-amber-300">${cellWeight.toFixed(4)}</span>
      </div>
      <div class="text-[10px] text-slate-400 mb-1 font-mono">
        y[${row}] (Value) × x[${col}] (Key)
      </div>
    `;

    if (contributing.length > 0) {
      tooltipContent += `
        <div class="text-[10px] text-slate-300 font-semibold mb-1 uppercase tracking-wider">Contributing Fact Writes:</div>
        <div class="space-y-1">
          ${contributing
          .map(
            (c) =>
              `<div class="flex justify-between items-center text-[10px] bg-[#070a10] border border-[#1c2638] px-1.5 py-0.5 rounded">
                  <span class="text-slate-200 truncate mr-2">${c.fact}</span>
                  <span class="font-mono text-emerald-400 font-medium">+${c.contrib.toFixed(3)}</span>
                </div>`
          )
          .join("")}
        </div>
      `;
    } else {
      tooltipContent += `
        <div class="text-[10px] text-slate-500 italic">No stored facts active at this synapse</div>
      `;
    }

    tooltip.innerHTML = tooltipContent;
    tooltip.style.display = "block";

    const container = canvas.parentElement;
    const contRect = container.getBoundingClientRect();
    const tipX = e.clientX - contRect.left + 16;
    const tipY = e.clientY - contRect.top + 16;
    tooltip.style.left = `${Math.min(tipX, contRect.width - 270)}px`;
    tooltip.style.top = `${Math.min(tipY, contRect.height - 130)}px`;
  });

  canvas.addEventListener("mouseleave", () => {
    tooltip.style.display = "none";
  });
}

/**
 * Draggable Floating HUD Controller
 */
function setupDraggableHUD() {
  const hud = document.getElementById("tour-overlay-container");
  const handle = document.getElementById("tour-drag-handle");
  if (!hud || !handle) return;

  let isDragging = false;
  let startX = 0, startY = 0;
  let initialLeft = 0, initialTop = 0;

  function onStart(e) {
    if (e.target.closest("button") || e.target.closest("a")) return;

    isDragging = true;
    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    const clientY = e.touches ? e.touches[0].clientY : e.clientY;

    startX = clientX;
    startY = clientY;

    const rect = hud.getBoundingClientRect();
    initialLeft = rect.left;
    initialTop = rect.top;

    hud.style.bottom = "auto";
    hud.style.right = "auto";
    hud.style.left = `${initialLeft}px`;
    hud.style.top = `${initialTop}px`;

    handle.style.cursor = "grabbing";
    document.body.style.userSelect = "none";

    window.addEventListener("mousemove", onMove);
    window.addEventListener("mouseup", onEnd);
    window.addEventListener("touchmove", onMove, { passive: false });
    window.addEventListener("touchend", onEnd);
  }

  function onMove(e) {
    if (!isDragging) return;
    if (e.cancelable) e.preventDefault();

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    const clientY = e.touches ? e.touches[0].clientY : e.clientY;

    const dx = clientX - startX;
    const dy = clientY - startY;

    let newLeft = initialLeft + dx;
    let newTop = initialTop + dy;

    const hudWidth = hud.offsetWidth;
    const hudHeight = hud.offsetHeight;

    newLeft = Math.max(12, Math.min(window.innerWidth - hudWidth - 12, newLeft));
    newTop = Math.max(12, Math.min(window.innerHeight - hudHeight - 12, newTop));

    hud.style.left = `${newLeft}px`;
    hud.style.top = `${newTop}px`;
  }

  function onEnd() {
    isDragging = false;
    handle.style.cursor = "grab";
    document.body.style.userSelect = "";
    window.removeEventListener("mousemove", onMove);
    window.removeEventListener("mouseup", onEnd);
    window.removeEventListener("touchmove", onMove);
    window.removeEventListener("touchend", onEnd);
  }

  handle.addEventListener("mousedown", onStart);
  handle.addEventListener("touchstart", onStart, { passive: true });
}

/**
 * Update the Autoplay Top Header Button UI
 */
function updateAutoplayButtonUI() {
  const dot = document.getElementById("autoplay-dot");
  const text = document.getElementById("autoplay-text");
  const btn = document.getElementById("btn-autoplay");
  if (!dot || !text || !btn) return;

  if (state.autoplayActive) {
    dot.className = "w-2 h-2 rounded-full bg-emerald-400 animate-pulse";
    text.textContent = "Autoplay: ON";
    btn.classList.add("border-emerald-500/50", "bg-emerald-950/40");
    btn.classList.remove("border-[#1c2638]", "bg-[#152033]");
  } else {
    dot.className = "w-2 h-2 rounded-full bg-slate-500";
    text.textContent = "Autoplay: PAUSED";
    btn.classList.remove("border-emerald-500/50", "bg-emerald-950/40");
    btn.classList.add("border-[#1c2638]", "bg-[#152033]");
  }
}

/**
 * Autoplay Cycle Stepper
 * Automatically shifts sliders to prove biological memory dynamics while user tests queries
 */
function stepAutoplay() {
  if (!state.autoplayActive || state.tourActive) return;

  const config = AUTOPLAY_CYCLE[state.autoplayStepIndex];
  state.autoplayStepIndex = (state.autoplayStepIndex + 1) % AUTOPLAY_CYCLE.length;

  state.factsCount = config.facts;
  state.k = config.k;
  state.lambda = config.lambda;
  state.contextTokens = config.context;

  // Synchronize DOM Sliders & Text Displays
  const sliderFacts = document.getElementById("slider-facts");
  const displayFacts = document.getElementById("val-facts");
  const sliderK = document.getElementById("slider-k");
  const displayK = document.getElementById("val-k");
  const sliderLambda = document.getElementById("slider-lambda");
  const displayLambda = document.getElementById("val-lambda");
  const sliderContext = document.getElementById("slider-context");

  if (sliderFacts) sliderFacts.value = config.facts;
  if (displayFacts) displayFacts.textContent = `${config.facts} / ${state.facts.length}`;

  if (sliderK) sliderK.value = config.k;
  if (displayK) displayK.textContent = `k = ${config.k} (${((config.k / N) * 100).toFixed(1)}%)`;

  if (sliderLambda) sliderLambda.value = config.lambda.toFixed(2);
  if (displayLambda) displayLambda.textContent = `λ = ${config.lambda.toFixed(2)}`;

  if (sliderContext) sliderContext.value = config.context;

  renderFactList();
  updateQueryDropdown();
  updateFormulaDisplay();
  updateMemoryMeter();

  // Pulse new matrix state with rank-1 flash
  recomputeMatrix(true);
}

function startAutoplay() {
  if (state.autoplayIntervalId) {
    clearInterval(state.autoplayIntervalId);
  }
  state.autoplayActive = true;
  updateAutoplayButtonUI();
  state.autoplayIntervalId = setInterval(stepAutoplay, 2400);
}

function stopAutoplay() {
  state.autoplayActive = false;
  if (state.autoplayIntervalId) {
    clearInterval(state.autoplayIntervalId);
    state.autoplayIntervalId = null;
  }
  updateAutoplayButtonUI();
}

function toggleAutoplay() {
  if (state.autoplayActive) {
    stopAutoplay();
  } else {
    // If walkthrough is running, close it so autoplay can take the canvas
    if (state.tourActive) {
      endGuidedTour();
    } else {
      startAutoplay();
    }
  }
}

/**
 * Render precomputed PyTorch benchmarks into View 2 (Deep Dive)
 */
function renderPyTorchBenchmarks() {
  const tableBody = document.getElementById("benchmark-table-body");
  const memoryStrip = document.getElementById("benchmark-memory-strip");

  if (tableBody && benchmarksData?.capacity_vs_facts) {
    tableBody.innerHTML = benchmarksData.capacity_vs_facts
      .slice(0, 8)
      .map((row) => {
        const bdhAcc = (row.bdh_sparse.accuracy_mean * 100).toFixed(1);
        const denseAcc = (row.dense_linear.accuracy_mean * 100).toFixed(1);
        const kvAcc = (row.softmax_kv.accuracy_mean * 100).toFixed(1);
        const bdhCos = row.bdh_sparse.cosine_mean.toFixed(4);

        return `
          <tr class="hover:bg-[#0c1322] transition-colors">
            <td class="p-2 font-semibold text-slate-200">${row.num_facts} items</td>
            <td class="p-2 text-emerald-400">${kvAcc}%</td>
            <td class="p-2 ${parseFloat(denseAcc) < 50 ? 'text-rose-400' : 'text-amber-400'}">${denseAcc}%</td>
            <td class="p-2 text-sky-300 font-bold">${bdhAcc}%</td>
            <td class="p-2 text-teal-300">${bdhCos}</td>
          </tr>
        `;
      })
      .join("");
  }

  if (memoryStrip && benchmarksData?.memory_vs_context) {
    const selectedPoints = [100, 1000, 5000, 10000];
    const filtered = benchmarksData.memory_vs_context.filter((d) =>
      selectedPoints.includes(d.context_tokens)
    );

    memoryStrip.innerHTML = filtered
      .map((d) => `
        <div class="bg-[#070a10] border border-[#1c2638] p-2.5 rounded-lg">
          <span class="text-[10px] text-slate-500 block">T = ${d.context_tokens.toLocaleString()}</span>
          <span class="text-rose-400 font-bold block text-xs mt-0.5">KV: ${d.kv_cache_kb} KB</span>
          <span class="text-sky-300 font-bold block text-xs">BDH: ${d.bdh_kb} KB</span>
          <span class="text-[9px] text-amber-400 block mt-1">${d.ratio_kv_to_bdh}× savings</span>
        </div>
      `)
      .join("");
  }
}

/**
 * Concurrent Dual-Slider Animator
 */
function animateDualSliders(fromFacts, toFacts, fromK, toK, durationMs, onUpdate) {
  if (state.tourRaf) {
    cancelAnimationFrame(state.tourRaf);
    state.tourRaf = null;
  }

  const startT = performance.now();
  const sliderFacts = document.getElementById("slider-facts");
  const displayFacts = document.getElementById("val-facts");
  const sliderK = document.getElementById("slider-k");
  const displayK = document.getElementById("val-k");

  function step(now) {
    const progress = Math.min(1, (now - startT) / durationMs);
    const curFacts = Math.round(fromFacts + (toFacts - fromFacts) * progress);
    const curK = Math.round(fromK + (toK - fromK) * progress);

    if (sliderFacts) sliderFacts.value = curFacts;
    if (displayFacts) displayFacts.textContent = `${curFacts} / ${state.facts.length}`;

    if (sliderK) sliderK.value = curK;
    if (displayK) displayK.textContent = `k = ${curK} (${((curK / N) * 100).toFixed(1)}%)`;

    onUpdate(curFacts, curK);

    if (progress < 1) {
      state.tourRaf = requestAnimationFrame(step);
    } else {
      state.tourRaf = null;
    }
  }
  state.tourRaf = requestAnimationFrame(step);
}

/**
 * Single-Slider Animator for Step 3
 */
function animateSingleSlider(startVal, endVal, durationMs, sliderId, displayId, onUpdate) {
  if (state.tourRaf) {
    cancelAnimationFrame(state.tourRaf);
    state.tourRaf = null;
  }

  const startT = performance.now();
  const sliderElem = document.getElementById(sliderId);
  const displayElem = document.getElementById(displayId);

  function step(now) {
    const progress = Math.min(1, (now - startT) / durationMs);
    const currentVal = Math.round(startVal + (endVal - startVal) * progress);

    if (sliderElem) sliderElem.value = currentVal;
    if (displayElem) {
      if (sliderId === "slider-k") {
        displayElem.textContent = `k = ${currentVal} (${((currentVal / N) * 100).toFixed(1)}%)`;
      } else {
        displayElem.textContent = `${currentVal} / ${state.facts.length}`;
      }
    }
    onUpdate(currentVal);

    if (progress < 1) {
      state.tourRaf = requestAnimationFrame(step);
    } else {
      state.tourRaf = null;
    }
  }
  state.tourRaf = requestAnimationFrame(step);
}

/**
 * Guided Tour Controller
 */
function startGuidedTour() {
  stopAutoplay();

  if (state.tourRaf) {
    cancelAnimationFrame(state.tourRaf);
    state.tourRaf = null;
  }

  state.tourActive = true;
  state.tourStep = 1;
  const overlay = document.getElementById("tour-overlay-container");
  if (overlay) overlay.classList.remove("hidden");

  renderTourStep(1);
}

function renderTourStep(step) {
  if (state.tourRaf) {
    cancelAnimationFrame(state.tourRaf);
    state.tourRaf = null;
  }

  state.tourStep = step;
  const titleElem = document.getElementById("tour-title");
  const descElem = document.getElementById("tour-desc");
  const nextBtn = document.getElementById("tour-next-btn");
  const stepDots = document.getElementById("tour-step-dots");

  if (stepDots) {
    stepDots.innerHTML = [1, 2, 3]
      .map(
        (s) =>
          `<div class="w-2 h-2 rounded-full transition-colors ${s === step ? "bg-sky-400 ring-2 ring-sky-400/40" : "bg-[#1c2638]"}"></div>`
      )
      .join("");
  }

  if (step === 1) {
    state.k = 4;
    state.factsCount = 3;
    state.lambda = 1.0;
    state.selectedQueryKey = BASE_FACTS[0]?.key || "Paris";

    const kSlider = document.getElementById("slider-k");
    const kDisplay = document.getElementById("val-k");
    const factsSlider = document.getElementById("slider-facts");
    const factsDisplay = document.getElementById("val-facts");
    const lambdaSlider = document.getElementById("slider-lambda");
    const lambdaDisplay = document.getElementById("val-lambda");

    if (kSlider) kSlider.value = 4;
    if (kDisplay) kDisplay.textContent = `k = 4 (6.2%)`;
    if (factsSlider) factsSlider.value = 3;
    if (factsDisplay) factsDisplay.textContent = `3 / ${state.facts.length}`;
    if (lambdaSlider) lambdaSlider.value = 1.0;
    if (lambdaDisplay) lambdaDisplay.textContent = `λ = 1.00`;

    renderFactList();
    updateQueryDropdown();
    updateFormulaDisplay();
    updateMemoryMeter();
    recomputeMatrix(true);

    if (titleElem) titleElem.textContent = "Step 1: Clean Associative Memory (BDH Baseline)";
    if (descElem) {
      descElem.innerHTML = `
        <p><strong>Input → Synapses → Output:</strong> 3 facts are written to the matrix.</p>
        <p class="text-slate-400">Querying <span class="font-mono text-sky-300">"${state.selectedQueryKey}"</span> retrieves the target with <strong>100% confidence</strong>. Because activation is sparse (<span class="font-mono text-sky-300">k=4, 6.2%</span>), the outer products occupy isolated synapses with zero crosstalk.</p>
      `;
    }
    if (nextBtn) nextBtn.textContent = "Step 2: Trigger Catastrophic Interference →";

  } else if (step === 2) {
    if (titleElem) titleElem.textContent = "Step 2: Dual Overload → Catastrophic Interference";
    if (descElem) {
      descElem.innerHTML = `
        <p>Watch both sliders animate simultaneously: <strong>Stored Facts (3 → 15)</strong> and <strong>Sparsity (k=4 → k=32, 50% Dense)</strong>.</p>
        <p class="text-slate-400">With 15 facts and dense representations, shared synapses are completely flooded. The candidate spectrum blurs, and recall collapses into <span class="text-rose-400 font-bold">CATASTROPHIC INTERFERENCE</span>!</p>
      `;
    }
    if (nextBtn) nextBtn.textContent = "Step 3: See BDH Sparsity Rescue Memory →";

    animateDualSliders(3, 15, 4, 32, 2400, (factsVal, kVal) => {
      state.factsCount = factsVal;
      state.k = kVal;
      renderFactList();
      updateQueryDropdown();
      recomputeMatrix(false);
    });

  } else if (step === 3) {
    state.factsCount = 8;
    const factsSlider = document.getElementById("slider-facts");
    const factsDisplay = document.getElementById("val-facts");
    if (factsSlider) factsSlider.value = 8;
    if (factsDisplay) factsDisplay.textContent = `8 / ${state.facts.length}`;
    renderFactList();
    updateQueryDropdown();

    if (titleElem) titleElem.textContent = "Step 3: How BDH Sparsity Rescues Recall";
    if (descElem) {
      descElem.innerHTML = `
        <p>Keeping <strong>8 facts</strong> in memory, watch the <strong>Sparsity slider slide back down from k=32 → k=3 (~4.7%)</strong>.</p>
        <p class="text-slate-400">By activating only ~5% of neurons, concept vectors project into vast orthogonal subspaces. Synaptic crosstalk vanishes, and high-fidelity recall is restored!</p>
      `;
    }
    if (nextBtn) nextBtn.textContent = "Explore Interactive Sandbox 🎉";

    animateSingleSlider(32, 3, 2000, "slider-k", "val-k", (val) => {
      state.k = val;
      recomputeMatrix(false);
    });
  }
}

function advanceGuidedTour() {
  if (state.tourStep === 1) renderTourStep(2);
  else if (state.tourStep === 2) renderTourStep(3);
  else endGuidedTour();
}

function endGuidedTour() {
  state.tourActive = false;
  if (state.tourRaf) {
    cancelAnimationFrame(state.tourRaf);
    state.tourRaf = null;
  }
  const overlay = document.getElementById("tour-overlay-container");
  if (overlay) overlay.classList.add("hidden");

  // When walkthrough is finished or skipped, Autoplay turns ON automatically!
  startAutoplay();
}
window.endGuidedTour = endGuidedTour;

/**
 * Setup Event Listeners for UI Controls
 */
function setupEventListeners() {
  const kSlider = document.getElementById("slider-k");
  const kDisplay = document.getElementById("val-k");
  const factsSlider = document.getElementById("slider-facts");
  const factsDisplay = document.getElementById("val-facts");
  const lambdaSlider = document.getElementById("slider-lambda");
  const lambdaDisplay = document.getElementById("val-lambda");
  const contextSlider = document.getElementById("slider-context");
  const autoplayBtn = document.getElementById("btn-autoplay");

  // Autoplay button listener
  if (autoplayBtn) {
    autoplayBtn.addEventListener("click", () => {
      toggleAutoplay();
    });
  }

  // Sparsity slider
  if (kSlider && kDisplay) {
    kSlider.addEventListener("input", (e) => {
      const val = parseInt(e.target.value, 10);
      state.k = val;
      const pct = ((val / N) * 100).toFixed(1);
      kDisplay.textContent = `k = ${val} (${pct}%)`;
      recomputeMatrix(false);
    });
  }

  // Facts written slider
  if (factsSlider && factsDisplay) {
    factsSlider.max = state.facts.length;
    factsSlider.addEventListener("input", (e) => {
      const val = parseInt(e.target.value, 10);
      state.factsCount = val;
      factsDisplay.textContent = `${val} / ${state.facts.length}`;
      renderFactList();
      updateQueryDropdown();
      recomputeMatrix(true);
    });
  }

  // Decay lambda slider
  if (lambdaSlider && lambdaDisplay) {
    lambdaSlider.addEventListener("input", (e) => {
      const val = parseFloat(e.target.value);
      state.lambda = val;
      lambdaDisplay.textContent = `λ = ${val.toFixed(2)}`;
      updateFormulaDisplay();
      recomputeMatrix(false);
    });
  }

  // Context length T scaling slider
  if (contextSlider) {
    contextSlider.addEventListener("input", (e) => {
      state.contextTokens = parseInt(e.target.value, 10);
      updateMemoryMeter();
    });
  }

  // Fact Search filter input
  const searchInput = document.getElementById("search-facts");
  if (searchInput) {
    searchInput.addEventListener("input", (e) => {
      factSearchQuery = e.target.value;
      renderFactList();
    });
  }

  // Quick Simulation Presets
  const presetBdh = document.getElementById("preset-bdh");
  const presetStress = document.getElementById("preset-stress");
  const presetDense = document.getElementById("preset-dense");

  if (presetBdh) {
    presetBdh.addEventListener("click", () => {
      stopAutoplay();
      state.k = 3;
      state.factsCount = 4;
      state.lambda = 1.0;
      if (kSlider) kSlider.value = 3;
      if (kDisplay) kDisplay.textContent = `k = 3 (4.7%)`;
      if (factsSlider) factsSlider.value = 4;
      if (factsDisplay) factsDisplay.textContent = `4 / ${state.facts.length}`;
      if (lambdaSlider) lambdaSlider.value = 1.0;
      if (lambdaDisplay) lambdaDisplay.textContent = `λ = 1.00`;
      renderFactList();
      updateQueryDropdown();
      updateFormulaDisplay();
      recomputeMatrix(true);
    });
  }

  if (presetStress) {
    presetStress.addEventListener("click", () => {
      stopAutoplay();
      state.k = 3;
      state.factsCount = Math.min(18, state.facts.length);
      state.lambda = 1.0;
      if (kSlider) kSlider.value = 3;
      if (kDisplay) kDisplay.textContent = `k = 3 (4.7%)`;
      if (factsSlider) factsSlider.value = state.factsCount;
      if (factsDisplay) factsDisplay.textContent = `${state.factsCount} / ${state.facts.length}`;
      if (lambdaSlider) lambdaSlider.value = 1.0;
      if (lambdaDisplay) lambdaDisplay.textContent = `λ = 1.00`;
      renderFactList();
      updateQueryDropdown();
      updateFormulaDisplay();
      recomputeMatrix(true);
    });
  }

  if (presetDense) {
    presetDense.addEventListener("click", () => {
      stopAutoplay();
      state.k = 32;
      state.factsCount = 4;
      state.lambda = 1.0;
      if (kSlider) kSlider.value = 32;
      if (kDisplay) kDisplay.textContent = `k = 32 (50.0%)`;
      if (factsSlider) factsSlider.value = 4;
      if (factsDisplay) factsDisplay.textContent = `4 / ${state.facts.length}`;
      if (lambdaSlider) lambdaSlider.value = 1.0;
      if (lambdaDisplay) lambdaDisplay.textContent = `λ = 1.00`;
      renderFactList();
      updateQueryDropdown();
      updateFormulaDisplay();
      recomputeMatrix(true);
    });
  }

  // Reset button
  const resetBtn = document.getElementById("btn-reset");
  if (resetBtn) {
    resetBtn.addEventListener("click", () => {
      stopAutoplay();
      state.k = 4;
      state.factsCount = 3;
      state.lambda = 1.0;
      state.contextTokens = 1000;
      state.facts = JSON.parse(JSON.stringify(BASE_FACTS));
      state.selectedQueryKey = BASE_FACTS[0]?.key || "Paris";
      state.cache.clear();
      seedBackendVectors();

      if (kSlider) kSlider.value = 4;
      if (kDisplay) kDisplay.textContent = `k = 4 (6.2%)`;
      if (factsSlider) factsSlider.value = 3;
      if (factsDisplay) factsDisplay.textContent = `3 / ${state.facts.length}`;
      if (lambdaSlider) lambdaSlider.value = 1.0;
      if (lambdaDisplay) lambdaDisplay.textContent = `λ = 1.00`;
      if (contextSlider) contextSlider.value = 1000;

      factSearchQuery = "";
      if (searchInput) searchInput.value = "";

      updateFormulaDisplay();
      renderFactList();
      updateQueryDropdown();
      updateMemoryMeter();
      recomputeMatrix(true);
    });
  }

  // Query dropdown select
  const querySelect = document.getElementById("query-select");
  if (querySelect) {
    querySelect.addEventListener("change", (e) => {
      state.selectedQueryKey = e.target.value;
      renderRecall();
    });
  }

  // Recall button
  const recallBtn = document.getElementById("btn-recall");
  if (recallBtn) {
    recallBtn.addEventListener("click", () => {
      recallBtn.classList.add("scale-95");
      setTimeout(() => recallBtn.classList.remove("scale-95"), 140);
      renderRecall();
    });
  }

  // Tab switching
  const tabMatrix = document.getElementById("tab-matrix");
  const tabDeepDive = document.getElementById("tab-deepdive");
  const viewMatrix = document.getElementById("view-matrix");
  const viewDeepDive = document.getElementById("view-deepdive");

  function switchTab(tab) {
    state.currentTab = tab;
    if (tab === "matrix") {
      tabMatrix.classList.add("bg-sky-600", "text-white");
      tabMatrix.classList.remove("text-slate-400", "hover:text-slate-200");
      tabDeepDive.classList.remove("bg-sky-600", "text-white");
      tabDeepDive.classList.add("text-slate-400", "hover:text-slate-200");

      viewMatrix.classList.remove("hidden");
      viewDeepDive.classList.add("hidden");
      renderMatrix();
    } else {
      tabDeepDive.classList.add("bg-sky-600", "text-white");
      tabDeepDive.classList.remove("text-slate-400", "hover:text-slate-200");
      tabMatrix.classList.remove("bg-sky-600", "text-white");
      tabMatrix.classList.add("text-slate-400", "hover:text-slate-200");

      viewMatrix.classList.add("hidden");
      viewDeepDive.classList.remove("hidden");
      renderDeepDiveKaTeX();
      renderPyTorchBenchmarks();
    }
  }

  if (tabMatrix && tabDeepDive) {
    tabMatrix.addEventListener("click", () => switchTab("matrix"));
    tabDeepDive.addEventListener("click", () => switchTab("deepdive"));
  }

  const setSparsity3Btn = document.getElementById("btn-set-k-3");
  if (setSparsity3Btn) {
    setSparsity3Btn.addEventListener("click", () => {
      stopAutoplay();
      state.k = 3;
      if (kSlider) kSlider.value = 3;
      if (kDisplay) kDisplay.textContent = `k = 3 (4.7%)`;
      switchTab("matrix");
      recomputeMatrix(true);
    });
  }

  const tourHeaderBtn = document.getElementById("btn-start-tour");
  if (tourHeaderBtn) {
    tourHeaderBtn.addEventListener("click", () => {
      startGuidedTour();
    });
  }

  const openSpecsBtn = document.getElementById("btn-open-specs");
  const specsModalContainer = document.getElementById("specs-modal-container");
  const specsCloseBtn = document.getElementById("specs-close-btn");
  const specsCloseBottomBtn = document.getElementById("specs-close-bottom-btn");

  function openSpecsModal() {
    if (specsModalContainer) {
      specsModalContainer.classList.remove("hidden");
    }
  }

  function closeSpecsModal() {
    if (specsModalContainer) {
      specsModalContainer.classList.add("hidden");
    }
  }

  if (openSpecsBtn) {
    openSpecsBtn.addEventListener("click", openSpecsModal);
  }
  if (specsCloseBtn) {
    specsCloseBtn.addEventListener("click", closeSpecsModal);
  }
  if (specsCloseBottomBtn) {
    specsCloseBottomBtn.addEventListener("click", closeSpecsModal);
  }
  if (specsModalContainer) {
    specsModalContainer.addEventListener("click", (e) => {
      if (e.target === specsModalContainer) {
        closeSpecsModal();
      }
    });
  }
  window.addEventListener("keydown", (e) => {
    if (e.key === "Escape") {
      closeSpecsModal();
    }
  });

  const tourSkipBtn = document.getElementById("tour-skip-btn");
  const tourSkipBottomBtn = document.getElementById("tour-skip-bottom-btn");
  const tourNextBtn = document.getElementById("tour-next-btn");
  if (tourSkipBtn) {
    tourSkipBtn.addEventListener("click", () => endGuidedTour());
  }
  if (tourSkipBottomBtn) {
    tourSkipBottomBtn.addEventListener("click", () => endGuidedTour());
  }
  if (tourNextBtn) {
    tourNextBtn.addEventListener("click", () => advanceGuidedTour());
  }
}

/**
 * Render LaTeX in BDH Deep Dive view
 */
function renderDeepDiveKaTeX() {
  if (typeof window === "undefined" || !window.katex) return;
  try {
    const eq1 = document.getElementById("katex-bdh-eq");
    const eq2 = document.getElementById("katex-synapse-eq");
    if (eq1) {
      window.katex.render(
        "\\mathcal{M}_{t} = \\lambda \\mathcal{M}_{t-1} + v_t k_t^\\top",
        eq1,
        { displayMode: true, throwOnError: false }
      );
    }
    if (eq2) {
      window.katex.render(
        "M \\leftarrow \\lambda M + y x^\\top",
        eq2,
        { displayMode: true, throwOnError: false }
      );
    }
  } catch (err) {
    console.error("KaTeX rendering error", err);
  }
}

/**
 * Initialize on Page Load
 */
window.addEventListener("DOMContentLoaded", () => {
  seedBackendVectors();
  renderFactList();
  updateQueryDropdown();
  updateFormulaDisplay();
  setupCanvasTooltip();
  setupEventListeners();
  setupDraggableHUD();
  updateMemoryMeter();
  updateAutoplayButtonUI();
  renderPyTorchBenchmarks();

  recomputeMatrix(true);

  // Initial load starts walkthrough HUD
  setTimeout(() => {
    startGuidedTour();
  }, 250);
});